version: "3"

services: 
    spotube:
      build: .
      volumes: 
        - /tmp/.X11-unix:/tmp/.X11-unix
      environment:
      # run `$ xhost local:root` in the host machine to get it work
        - DISPLAY=${DISPLAY}
      network_mode: host