name: Flutter Cross Build
on:
  push:
    branches: [build]
  workflow_dispatch:

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2.2.0
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y tar clang cmake ninja-build pkg-config libgtk-3-dev make libwebkit2gtk-4.0-dev keybinder-3.0 python3-pip python3-setuptools patchelf desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace fuse
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build linux
      - run: make deb
      - run: make tar
      - run: wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool
      - run: chmod +x /usr/local/bin/appimagetool
      - run: pip3 install appimage-builder
      - run: make appimage
      - uses: actions/upload-artifact@v2
        with:
          name: Spotube-Linux-Bundle
          path: |
            build/Spotube-linux-x86_64.deb
            build/Spotube-linux-x86_64.tar.xz
            build/Spotube-*-x86_64.AppImage
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2.2.0
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      - run: curl -o installer.exe https://jrsoftware.org/download.php/is.exe
      - run: ./installer.exe /verysilent /allusers /dir=iscc
      - run: ./iscc/iscc.exe scripts/windows-setup-creator.iss
      - run: rm -recurse iscc
      - run: rm installer.exe
      - uses: actions/upload-artifact@v2
        with:
          name: Spotube-Windows-Bundle
          path: build/installer/Spotube-windows-x86_64-setup.exe
